[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool]
[tool.poetry]
name = "squiral.py"
version = "0.1.0"
description = "squiral - square spiral"
authors = ["Sadık Kuzu"]

[tool.poetry.dependencies]
python = "^3.8.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
flake8 = "^6.0.0"
pre-commit = "^2.20.0"
