[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool]
[tool.poetry]
name = "squiral"
version = "0.1.0"
description = "squiral - square spiral"
authors = ["Sadık Kuzu"]

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^6.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^2.10.0"
flake8 = "^3.9.0"
