name: codecov workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code coverage
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: pip
    - name: Install requirements
      run: pip install -r requirements-dev.txt
    - name: Run tests and collect coverage
      run: pytest --cov=. --cov-report=term-missing --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
