name: Upgrade python and pre-commit dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  upgrader:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: pip

    - name: Run pip-compile, install requirements, and pre-commit autoupdate
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile -vU requirements-tool.in
        pip install -r requirements-tool.txt
        pip-compile -vU
        pip-compile -vU requirements-dev.in
        pip install -r requirements-dev.txt
        pre-commit autoupdate
        pre-commit run --all-files
        poetry update

    - name: Run tests
      run: pytest --cov=. --cov-report=term-missing

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ":arrow_up: Upgrade dependencies"
        branch: master
        commit_user_name: Upgrader
        commit_user_email: sadikkuzu@hotmail.com
        commit_author: Upgrader <sadikkuzu@hotmail.com>
