name: Upgrade dependencies into another branch

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"

jobs:
  branch-upgrader:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: upgrade-pip-pre-commit-poetry

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: pip

    - uses: actions/cache@v3
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}|pre-commit

    - name: Run pip-compile, install requirements, and pre-commit autoupdate
      run: |
        git pull
        git merge origin/master --no-edit
        git push
        ./scripts/upgrader.sh

    - name: Run tests
      run: pytest --cov=. --cov-report=term-missing

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ":arrow_up: Upgrade dependencies"
        branch: upgrade-pip-pre-commit-poetry
        commit_user_name: Upgrader
        commit_user_email: sadikkuzu@hotmail.com
        commit_author: Upgrader <sadikkuzu@hotmail.com>
